param(
  [string]$ProductionEnv = ".env.production",
  [string]$BackendLocalEnv = ".env.development.local",
  [string]$FrontendEnvPath = "..\WEB\web-frontend\.env.local"
)

$ErrorActionPreference = "Stop"

function Read-DotEnv {
  param([string]$Path)

  $values = [ordered]@{}
  if (-not (Test-Path -LiteralPath $Path)) {
    throw "Environment file not found: $Path"
  }

  foreach ($line in Get-Content -LiteralPath $Path) {
    $trimmed = $line.Trim()
    if (-not $trimmed -or $trimmed.StartsWith("#")) {
      continue
    }

    $separator = $line.IndexOf("=")
    if ($separator -lt 1) {
      continue
    }

    $key = $line.Substring(0, $separator).Trim()
    $value = $line.Substring($separator + 1)
    $values[$key] = $value
  }

  return $values
}

function Write-DotEnv {
  param(
    [string]$Path,
    [string[]]$Lines
  )

  $parent = Split-Path -Parent $Path
  if ($parent -and -not (Test-Path -LiteralPath $parent)) {
    New-Item -ItemType Directory -Path $parent | Out-Null
  }

  Set-Content -LiteralPath $Path -Value $Lines -Encoding UTF8
}

$prod = Read-DotEnv -Path $ProductionEnv
$frontend = if (Test-Path -LiteralPath $FrontendEnvPath) { Read-DotEnv -Path $FrontendEnvPath } else { @{} }

$backendKeys = @(
  "DATABASE_URL",
  "DB_DIALECT",
  "DB_HOST",
  "DB_PORT",
  "DB_NAME",
  "DB_USER",
  "DB_PASSWORD",
  "DB_SSL",
  "DB_SSL_REJECT_UNAUTHORIZED",
  "FIREBASE_USE_ADC",
  "FIREBASE_PROJECT_ID",
  "FIREBASE_DATABASE_URL",
  "FIREBASE_TYPE",
  "FIREBASE_PRIVATE_KEY_ID",
  "FIREBASE_PRIVATE_KEY",
  "FIREBASE_SERVICE_ACCOUNT_JSON",
  "FIRESTORE_SERVICE_ACCOUNT_JSON",
  "FIREBASE_CLIENT_EMAIL",
  "FIREBASE_CLIENT_ID",
  "FIREBASE_AUTH_URI",
  "FIREBASE_TOKEN_URI",
  "FIREBASE_AUTH_PROVIDER_CERT_URL",
  "FIREBASE_CLIENT_CERT_URL",
  "FIREBASE_UNIVERSE_DOMAIN",
  "SUPABASE_URL",
  "SUPABASE_ANON_KEY",
  "SUPABASE_PUBLISHABLE_KEY",
  "SUPABASE_KEY",
  "SUPABASE_SECRET_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "SUPABASE_STORAGE_BUCKET",
  "SUPABASE_STORAGE_PUBLIC",
  "REDIS_URL",
  "REDIS_HOST",
  "REDIS_PORT",
  "REDIS_DB"
)

$backendLines = @(
  "# Local overrides generated from .env.production.",
  "# This file is ignored by git.",
  "NODE_ENV=development",
  "PORT=4000",
  "API_VERSION=v1",
  "APP_NAME=Motsamai Web Backend",
  "APP_BASE_URL=http://localhost:4000",
  "FRONTEND_URL=http://localhost:5173",
  "CORS_ORIGINS=http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173,https://motsamai.web.app,https://motsamai.firebaseapp.com",
  "SOCKET_CORS_ORIGINS=http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173,https://motsamai.web.app,https://motsamai.firebaseapp.com",
  "ENABLE_WEBSOCKETS=true",
  "LOG_LEVEL=debug",
  "DB_POOL_MAX=5",
  "DB_POOL_MIN=0",
  "DB_SYNC=true",
  "DB_SYNC_ALTER=true"
)

foreach ($key in $backendKeys) {
  if ($prod.Contains($key) -and $prod[$key] -ne "") {
    $backendLines += "$key=$($prod[$key])"
  }
}

Write-DotEnv -Path $BackendLocalEnv -Lines $backendLines

$frontendKeys = @(
  "SUPABASE_URL",
  "SUPABASE_ANON_KEY",
  "SUPABASE_PUBLISHABLE_KEY",
  "SUPABASE_KEY"
)

$frontendLines = @(
  "# Local overrides generated by web-backend/scripts/sync-local-env.ps1.",
  "# This file is ignored by git."
)

$frontendKeys = @(
  "VITE_APP_ENV",
  "VITE_APP_NAME",
  "VITE_API_URL",
  "VITE_API_BASE_URL",
  "VITE_BACKEND_URL",
  "VITE_WS_URL",
  "VITE_FIREBASE_API_KEY",
  "VITE_FIREBASE_AUTH_DOMAIN",
  "VITE_FIREBASE_DATABASE_URL",
  "VITE_FIREBASE_PROJECT_ID",
  "VITE_FIREBASE_MESSAGING_SENDER_ID",
  "VITE_FIREBASE_APP_ID",
  "VITE_FIREBASE_MEASUREMENT_ID",
  "VITE_SUPABASE_URL",
  "VITE_SUPABASE_PUBLISHABLE_KEY",
  "VITE_SUPABASE_STORAGE_BUCKET"
)

foreach ($key in $frontendKeys) {
  if ($frontend.Contains($key) -and $frontend[$key] -ne "") {
    $frontendLines += "$key=$($frontend[$key])"
  }
}

foreach ($key in $frontendKeys) {
  if ($prod.Contains($key) -and $prod[$key] -ne "") {
    $frontendLines += "VITE_$key=$($prod[$key])"
  }
}

Write-DotEnv -Path $FrontendEnvPath -Lines $frontendLines

Write-Host "Local env files synced:"
Write-Host "  Backend:  $BackendLocalEnv"
Write-Host "  Frontend: $FrontendEnvPath"
